sudo: required
language: node_js
node_js: 9.3.0
python: 3.6.3
cache:
- pip
- yarn
install: sudo -H pip install awscli --upgrade --ignore-installed six
before_script:
- yarn
- "./scripts/aws_credentials.sh"
script: yarn build
deploy:
- provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: hobbithobby.com
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: ap-southeast-1
  on:
    repo: TranHung92/reactive-LED-controller
- provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: www.hobbithobby.com
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: ap-southeast-1
  on:
    repo: TranHung92/reactive-LED-controller
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E3B65CB6EN9IKM --paths "/*"
env:
  global:
  - secure: SrMTyFEH8NEwi0HfCz0I/gab5y3frO+0gD75Zk3sYiYt6w3mat/eA/euaRZpILI7hWOeqWG4su7tz09NfwcrA9NbuJoUnFm/oi/qhMd3/ZC1f+SXs62XIOAkJhkH6eBOPvGhTKJSTjgmcSvFD7xdLyZGvpf0pRQke8CzYRJMmk80Eteg1xi+LjyugJnEz6+IabCFFrvj/DZWG6aIDMXKsF29iLtt8uyxqWcJLP4LT35C7wUruhY8m66WNhAmXxnQhBfQS1NlRSe3M32DmE9+kYhcJDy6TxCHkytyZ1VydX+t+/1iCEN+TR6E4gMwkNV9EJsGm6fM3zgDd+kCzlxxUo5fN399UoNFbHsN04UYAWWb6KP5hzAkp4GaVJh24OEDDOr/9LB01+OhJ9IPvIqYEB5gdZawvFOZZBAlgtKIf9x86kv+un/znY0sYpKdyMHw8DO9ETQthNxQNCyIrj//OrSkydLc/IuaN+ZctqzEcCjijXzy1oNtiOD+kqZ/IAPbZA7I0Ep9WJ76Nl6cCQYANsFOJsg2avk7QzNo3JQy9PrfzQtsN9vagBs4B1WjFAjBemNbq+xTD1XnjdynmKYpWdPNfFoW9GWm4Z88iFPCXgcqESivtcGQOxmHjuUmCCN8oHMxWSHshehYZYAbdnyTM19cI9dp3yutRJIWZ7Jp+ls=
  - secure: CFfZ8PM4Hgkutm3vfsqjgzckyIgPHfP+4xyOohIRQtfvThAFOH4Kh9DmrlZp9jtQWa5kJH//Q3ofHG+2GVIXy26qkl508EXVFfjqSWJe2yUTpNGzmKPCHDWQf7+jxlp9aJt2flCljDmhoJTJgjzu9JSvfIIo2nuwrgEqoHivmbgY1e3xxE2Un55MMQW8+r+8xfbkcSM1saXt6XsGH+NE2rQF1X4xI8ayfNGlkeJ6v6aTfwUpnLaW8yO42lSynQWz9baFkv8Ws8cO6AAzR7czsJCByTWFoOWxHzqhIlURD5psi6e8SGs8D0V58XnHKCceMLYzaTEUhbT0zg9yHCmKgSTbFKpVlbJOliHThTIGrsYZCiNSCbYtHq193nMJBQTJBoSYTuxC1/QhrGAJVzsm38SWjVyLE+aPBWe8+BqHVLrqOb5jk/WBBKAl644RVBzOOivprqQKMJom0RZ/5XF1jhz1cTaaJU5+vl4KzfHwV0LEdz3CgHjQJz4Kh8wQx2CiwcH98efbBN982sBblvilY73tvmmxhoc35cvznaZfoyZc9GGgGJRP11cQWRuh8UOZMtbTI5FcAw0lCXzGUbh3w5Q/5uGjK9iw+t2PjmxrSG+RnzJzrC4p8KU8zyFXL+ioeklpBbylrEEZRpveepIJQdJbTI7yBUFxivcZkNNZM0o=
